image: "ubuntu"

stages:
  - build
  - deploy

build:
  image: node:latest
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist

pages: # the job must be named pages
  image: node:latest
  stage: deploy
  script:
    - mv public public-vue # GitLab Pages hooks on the public folder
    - mv dist public # rename the dist folder (result of npm run build)
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up
  only:
    - master
  variables:
    GIT_STRATEGY: none
