image: "ubuntu"

cache:
  paths:
    - node_modules/

stages:
  - check
  - deploy

before_script:
  - rm -rf public-vue
  - rm -rf dist

check: # the job must be named pages
  image: node:latest
  stage: check
  script:
    - npm ci
    - npm run build
    - mv public public-vue
    - mv dist public
  artifacts:
    paths:
      - public

pages: # the job must be named pages
  image: node:latest
  stage: deploy
  script:
    - npm ci
    - npm run build
    - mv public public-vue # GitLab Pages hooks on the public folder
    - mv dist public # rename the dist folder (result of npm run build)
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up
  only:
    - master
