image: "vuejs/ci"

cache:
  paths:
    - .stack-work/

stages:
  - build

build:
  stage: build
  script:
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -7
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
    - sudo apt update
    - sudo apt install yarn -y
    - vue build
