image: "ubuntu"

stages:
  - check
  - deploy

before_script:
  - apt update
  - apt install tree -y
  - tree

check: # the job must be named pages
  image: node:latest
  stage: check
  script:
    - npm ci
    - npm run build
    - tree
  artifacts:
    paths:
      - public

pages: # the job must be named pages
  image: node:latest
  stage: deploy
  script:
    - mv public public-vue # GitLab Pages hooks on the public folder
    - mv dist public # rename the dist folder (result of npm run build)
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up
  only:
    - master
  variables:
    GIT_STRATEGY: none
