image: "ubuntu"

cache:
  paths:
    - .stack-work/

stages:
  - build

build:
  stage: build
  script:
    - apt update
    - apt upgrade -y
    - apt install curl gnupg -y
    - curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
    - apt update
    - apt install nodejs -y
    - apt install yarn -y
    - yarn global add @vue/cli
    - vue build
